
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import  StoreProvider  from "./store/StoreProvider";

const robotoSlab =  Roboto_Slab({subsets: ["latin"]});
export const metadata = {
  title: "The Book Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider><html lang="en">
      <body className={robotoSlab.className}>
        <NavBar/>
        {children}
        </body>
    </html>
    </StoreProvider>
  );
}
