
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
const robotoSlab =  Roboto_Slab({subsets: ["latin"]});

export const metadata = {
  title: "Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>
        <NavBar/>
        {children}
        </body>
    </html>
  );
}
